#!/usr/bin/env python3
"""Run deterministic rendering, audio, encoding and evidence generation. QC != aesthetic approval."""
import argparse,hashlib,importlib.util,json,os,re,shutil,subprocess,sys,traceback,wave,math,struct
from datetime import datetime,timezone
from pathlib import Path
from fractions import Fraction
from studio import validate,init
from audio import mix
from PIL import Image
HERE=Path(__file__).resolve().parent;ASSETS=HERE.parent/'assets'

def write(path,value):path.write_text(json.dumps(value,indent=2,ensure_ascii=False)+'\n',encoding='utf-8')
def sha(path):return hashlib.sha256(Path(path).read_bytes()).hexdigest()
def cmd(args,cwd=None):
    p=subprocess.run([str(a) for a in args],cwd=cwd,capture_output=True,text=True,encoding='utf-8',errors='replace')
    if p.returncode:raise RuntimeError(f'{args[0]} failed: {p.stderr[-2500:]}')
    return p

def demo(root):
    root=Path(root).resolve();init(root)
    spec=json.loads((root/'spec.json').read_text(encoding='utf-8'));spec.update(duration_frames=180,audio_mode='designed')
    spec['formats']=[{'id':'wide','width':960,'height':540,'safe':{'top':36,'right':48,'bottom':48,'left':48}},{'id':'vertical','width':540,'height':960,'safe':{'top':64,'right':40,'bottom':80,'left':40}}]
    copies=['Start with intent.','Connect the story.','Make every move matter.']
    spec['shots']=[{'id':f'S{i+1}','start':i*60,'end':(i+1)*60,'purpose':['Establish separate ideas','Show continuity through connection','Resolve into one clear message'][i],'entry_state':'nodes enter' if i==0 else 'previous node identity retained','exit_state':'stable reading hold','copy':copy,'asset_ids':[],'layouts':{'wide':'nodes left, title right','vertical':'nodes above, title below'},'transitions':[{'start':i*60,'end':i*60+12}]} for i,copy in enumerate(copies)]
    # Original music-like tone bed and transient accents; no external tracks.
    rate=48000;seconds=6
    with wave.open(str(root/'assets/original-tone.wav'),'wb') as wav:
        wav.setnchannels(1);wav.setsampwidth(2);wav.setframerate(rate)
        blocks=bytearray()
        for sample in range(rate*seconds):
            t=sample/rate;env=min(1,t/.08,(seconds-t)/.12)
            value=.08*env*(math.sin(2*math.pi*220*t)+.3*math.sin(2*math.pi*330*t))
            for onset in (0,2,4):
                delta=t-onset
                if 0<=delta<.15:value+=.1*math.exp(-delta*35)*math.sin(2*math.pi*660*delta)
            blocks+=struct.pack('<h',round(max(-1,min(1,value))*32767))
        wav.writeframes(blocks)
    spec['audio_cues']=[{'id':'original-bed','path':'assets/original-tone.wav','role':'music','start_frame':0,'duration_frames':180,'source_offset_seconds':0,'gain_db':0,'visual_event_frame':0,'intentional_offset_frames':0,'fade_in_seconds':.05,'fade_out_seconds':.12}]
    write(root/'spec.json',spec);write(root/'assets.json',{'assets':[{'id':'original-audio','path':'assets/original-tone.wav','role':'audio','provenance':'Original deterministic synthesized tone bed generated by pipeline.py demo','rights':'original','approved':True,'required':True}]})
    for name in ('pillow_composition.py','canvas-starter.html','render.mjs'):shutil.copy2(ASSETS/name,root/'src'/name)
    write(root/'package.json',{'private':True,'dependencies':{'playwright':'1.62.1'}})
    (root/'brief.md').write_text('# Generic motion study\n\nSix-second original graphic renderer exercise, 30fps, wide and vertical. No product UI, metrics or brand claims. Source-generated audio is original. Both engines are renderer examples, not client films.\n',encoding='utf-8')
    (root/'audio-plan.md').write_text('# Sound plan\n\nOriginal tone bed with accents at frames 0, 60, 120. Target -16 LUFS / -1 dBTP. Listening review required after rendering.\n',encoding='utf-8')
    print(f'Runnable demo prepared: {root}')

def module(path):
    m=importlib.util.spec_from_file_location('motion_project_composition',path);v=importlib.util.module_from_spec(m);m.loader.exec_module(v);return v

def pillow_frames(project,spec,fmt,out):
    render=module(project/'src/pillow_composition.py').render_frame
    samples=sorted({0,spec['duration_frames']-1,*[s['start'] for s in spec['shots']],*[min(s['end']-1,s['start']+12) for s in spec['shots']]})
    expected={f:hashlib.sha256(render(f,spec,fmt['id'],project).tobytes()).hexdigest() for f in samples}
    hashes={}
    for f in range(spec['duration_frames']):
        im=render(f,spec,fmt['id'],project)
        if im.size!=(fmt['width'],fmt['height']) or im.mode!='RGB':raise ValueError('Renderer output must match format dimensions and RGB mode')
        if f in expected:hashes[f]=hashlib.sha256(im.tobytes()).hexdigest()
        im.save(out/f'frame-{f:06d}.png')
    for f in reversed(samples):
        current=hashlib.sha256(render(f,spec,fmt['id'],project).tobytes()).hexdigest()
        if current!=expected[f] or hashes[f]!=expected[f]:raise ValueError('Seek/sequential decoded pixel mismatch')
    report={'engine':'pillow','algorithm':'sha256-decoded-rgb','checked_frames':samples,'seek_pass':True,'pillow':__import__('PIL').__version__,'note':'Same runtime only; not cross-platform pixel equivalence'}
    write(out/'render-check.json',report)
    return report

def probe(path,spec,fmt):
    data=json.loads(cmd(['ffprobe','-v','error','-count_frames','-show_streams','-show_format','-of','json',path]).stdout)
    videos=[s for s in data['streams'] if s['codec_type']=='video'];audios=[s for s in data['streams'] if s['codec_type']=='audio']
    if len(videos)!=1:raise ValueError('Expected exactly one video stream')
    v=videos[0];duration=spec['duration_frames']/spec['fps'];fail=[]
    for name,actual,expected in [('width',v['width'],fmt['width']),('height',v['height'],fmt['height']),('frame_count',int(v.get('nb_read_frames',-1)),spec['duration_frames']),('fps',Fraction(v['r_frame_rate']),Fraction(spec['fps'])),('codec',v['codec_name'],'h264'),('pixel_format',v['pix_fmt'],'yuv420p')]:
        if actual!=expected:fail.append(f'{name}: {actual} != {expected}')
    if abs(float(v['duration'])-duration)>1/spec['fps']+.001:fail.append('Video duration mismatch')
    if spec['audio_mode']=='designed':
        if len(audios)!=1:fail.append('Expected exactly one audio stream')
        elif abs(float(audios[0].get('duration',0))-duration)>1/spec['fps']+.03:fail.append('Audio duration mismatch')
    elif audios:fail.append('Silent film unexpectedly has audio')
    cmd(['ffmpeg','-v','error','-i',path,'-f','null','-'])
    if fail:raise ValueError('; '.join(fail))
    return {'technical_pass':True,'metadata':data,'full_decode_pass':True}

def execute(project,engine,run_id):
    root=Path(project).resolve();errors=validate(root)
    if errors:raise ValueError('; '.join(errors))
    for tool in ('ffmpeg','ffprobe'):
        if not shutil.which(tool):raise ValueError(f'Missing {tool}; install before running')
    if not re.fullmatch(r'[A-Za-z0-9][A-Za-z0-9._-]{0,63}',run_id):raise ValueError('run-id must be a safe directory name')
    spec=json.loads((root/'spec.json').read_text(encoding='utf-8'))
    if any(f['width']%2 or f['height']%2 for f in spec['formats']):raise ValueError('H.264 yuv420p requires even width and height')
    output=root/'out'/run_id
    if output.exists():raise ValueError('Run directory already exists; use another run-id')
    output.mkdir(parents=True)
    record={'status':'running','engine':engine,'spec_sha256':sha(root/'spec.json'),'asset_manifest_sha256':sha(root/'assets.json'),'completed':[],'error':None}
    write(output/'pipeline-state.json',record)
    try:
        mixed,aqc=(None,None)
        if spec['audio_mode']=='designed':mixed,aqc=mix(root,output/'audio');record['completed'].append('audio');write(output/'pipeline-state.json',record)
        samples=json.loads(cmd([sys.executable,HERE/'studio.py','samples',root]).stdout)
        write(output/'samples.json',samples)
        exports=[]
        for fmt in spec['formats']:
            if not re.fullmatch(r'[A-Za-z0-9][A-Za-z0-9_-]{0,63}',fmt['id']):raise ValueError('Format id must be a safe filename')
            folder=output/fmt['id'];frames=folder/'frames';frames.mkdir(parents=True)
            if engine=='pillow':pillow_frames(root,spec,fmt,frames)
            else:cmd(['node',root/'src/render.mjs','--spec',root/'spec.json','--html',root/'src/canvas-starter.html','--format',fmt['id'],'--out',frames],cwd=root)
            movie=folder/'film.mp4'
            args=['ffmpeg','-v','error','-framerate',spec['fps'],'-start_number','0','-i',frames/'frame-%06d.png']
            if mixed:args+=['-i',mixed]
            args+=['-map','0:v:0']
            if mixed:args+=['-map','1:a:0','-c:a','aac','-b:a','192k']
            args+=['-frames:v',spec['duration_frames'],'-c:v','libx264','-pix_fmt','yuv420p','-movflags','+faststart',movie]
            cmd(args)
            qc=probe(movie,spec,fmt)
            # Measure encoded audio too; lossy delivery can change true peak.
            if mixed:
                from audio import measurement
                observed=measurement(movie,aqc['targets']['integrated_lufs'],aqc['targets']['true_peak_db'])
                if float(observed['input_tp'])>aqc['targets']['true_peak_db']+.3:raise ValueError('Encoded audio exceeds true-peak tolerance')
                qc['encoded_audio_measurement']=observed
            shutil.copy2(frames/f'frame-{spec["duration_frames"]-1:06d}.png',folder/'poster.png')
            cmd([sys.executable,HERE/'contact_sheet.py','--stills',frames,'--samples',output/'samples.json','--output',folder/'contact-sheet.png'])
            # Phone-width evidence and transition playback extracts.
            with Image.open(folder/'poster.png') as im:im.resize((360,round(im.height*360/im.width))).save(folder/'phone-poster.png')
            transitions=folder/'transitions';transitions.mkdir()
            for i,shot in enumerate(spec['shots']):
                for j,tr in enumerate(shot.get('transitions',[])):
                    a=max(0,tr['start']-3);b=min(spec['duration_frames'],tr['end']+6)
                    cmd(['ffmpeg','-v','error','-i',movie,'-vf',f'trim=start_frame={a}:end_frame={b},setpts=PTS-STARTPTS','-an','-c:v','libx264','-pix_fmt','yuv420p',transitions/f'{i:02d}-{j:02d}.mp4'])
            qc.update({'visual_review':'pending','temporal_review':'pending','audio_listening':'pending' if mixed else 'not_applicable_intentional_silence','film_sha256':sha(movie)})
            write(folder/'qc.json',qc);exports.append({'format':fmt['id'],'film':str(movie.relative_to(output)),'sha256':sha(movie),'technical_pass':True})
            record['completed'].append(fmt['id']);write(output/'pipeline-state.json',record)
        sources={p.relative_to(root).as_posix():sha(p) for p in (root/'src').rglob('*') if p.is_file() and '__pycache__' not in str(p)}
        for name in ('package.json','package-lock.json','requirements.txt'):
            if (root/name).is_file():sources[name]=sha(root/name)
        manifests=json.loads((root/'assets.json').read_text(encoding='utf-8'))
        assets={a['path']:sha(root/a['path']) for a in manifests['assets'] if (root/a['path']).is_file()}
        versions={'python':sys.version,'ffmpeg':cmd(['ffmpeg','-version']).stdout.splitlines()[0],'pillow':__import__('PIL').__version__,'font_override':os.environ.get('MOTION_FONT_PATH')}
        for font in (os.environ.get('MOTION_FONT_PATH',''),'/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf','C:/Windows/Fonts/arial.ttf','/System/Library/Fonts/Supplemental/Arial.ttf'):
            if font and Path(font).is_file():versions['resolved_font']={'path':font,'sha256':sha(font)};break
        write(output/'manifest.json',{'version':'1.2.0','engine':engine,'spec_sha256':record['spec_sha256'],'source_hashes':sources,'asset_hashes':assets,'runtime':versions,'exports':exports,'review_status':'pending','final':False})
        write(output/'review.json',{'spec_sha256':record['spec_sha256'],'film_hashes':{e['format']:e['sha256'] for e in exports},'visual':'pending','temporal':'pending','audio':'pending' if mixed else 'not_applicable_intentional_silence','defects':[]})
        record['status']='technical_pass_review_pending';write(output/'pipeline-state.json',record)
        (output/'delivery.md').write_text(f'# Rendered draft\n\nEngine: {engine}. All requested formats encoded and passed structural/decode checks.\n\nVisual/temporal review and required audio listening remain pending. Inspect per-format contact sheets, phone posters, transition clips and the full films. Machine QC does not approve artistic quality.\n\nReproduce with a fresh run id: python3 <motion-studio-dir>/scripts/pipeline.py run <project> --engine {engine} --run-id <new-id>\n\nSource and asset hashes are in manifest.json.\n',encoding='utf-8')
        print(json.dumps({'output':str(output),'status':record['status'],'formats':[e['format'] for e in exports]},indent=2))
        return output
    except Exception as e:
        record.update(status='failed',error=str(e));write(output/'pipeline-state.json',record);raise

def main():
    p=argparse.ArgumentParser(description=__doc__);sub=p.add_subparsers(dest='command',required=True)
    d=sub.add_parser('demo');d.add_argument('project')
    r=sub.add_parser('run');r.add_argument('project');r.add_argument('--engine',choices=['pillow','canvas'],default='pillow');r.add_argument('--run-id',default=datetime.now(timezone.utc).strftime('%Y%m%dT%H%M%S%fZ'))
    a=p.parse_args()
    try:
        if a.command=='demo':demo(a.project)
        else:execute(a.project,a.engine,a.run_id)
    except (OSError,ValueError,RuntimeError,StopIteration,subprocess.CalledProcessError) as e:p.exit(1,f'Pipeline failed: {e}\n')
if __name__=='__main__':main()
